package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/term"
)

func runSetup(args []string, _ *slog.Logger) error {
	fs := flag.NewFlagSet("setup", flag.ExitOnError)
	emailFlag := fs.String("email", "", "admin email address")
	passwordFlag := fs.String("password", "", "admin password (min 8 chars)")
	secretFlag := fs.String("secret", "", "session secret (auto-generated if omitted)")
	apiKeyFlag := fs.String("anthropic-key", "", "Anthropic API key (optional, for AI features)")
	outFlag := fs.String("out", ".env", "output file path")
	fs.Parse(args)

	email := *emailFlag
	password := *passwordFlag
	secret := *secretFlag
	anthropicKey := *apiKeyFlag
	envPath := *outFlag

	if email != "" && password != "" {
		return writeEnvFile(email, password, secret, anthropicKey, envPath)
	}

	fmt.Println()
	fmt.Println("┌──────────────────────────────────────────────────────┐")
	fmt.Println("│  ChainWarden Setup                                 │")
	fmt.Println("│                                                      │")
	fmt.Println("│  Configure dashboard credentials and API settings.   │")
	fmt.Println("│  Writes to .env in the current directory.            │")
	fmt.Println("│                                                      │")
	fmt.Println("│  Non-interactive:                                    │")
	fmt.Println("│    cwctl setup --email=you@x.com --password=secret   │")
	fmt.Println("└──────────────────────────────────────────────────────┘")
	fmt.Println()

	reader := bufio.NewReader(os.Stdin)

	if email == "" {
		email = setupPrompt(reader, "Admin email", os.Getenv("CW_ADMIN_EMAIL"))
	}
	if email == "" {
		return fmt.Errorf("email is required — or use: cwctl setup --email=you@example.com --password=secret")
	}

	if password == "" {
		password = readPassword()
	}
	if password == "" {
		return fmt.Errorf("password is required — or use: cwctl setup --email=you@example.com --password=secret")
	}
	if len(password) < 8 {
		return fmt.Errorf("password must be at least 8 characters")
	}

	if anthropicKey == "" {
		anthropicKey = setupPrompt(reader, "Anthropic API key (for AI features, optional)", os.Getenv("ANTHROPIC_API_KEY"))
	}

	return writeEnvFile(email, password, secret, anthropicKey, envPath)
}

func readPassword() string {
	fmt.Print("  Admin password: ")
	if term.IsTerminal(int(os.Stdin.Fd())) {
		passBytes, err := term.ReadPassword(int(os.Stdin.Fd()))
		fmt.Println()
		if err == nil {
			return strings.TrimSpace(string(passBytes))
		}
	}
	fmt.Println()
	fmt.Print("  Admin password (visible): ")
	reader := bufio.NewReader(os.Stdin)
	line, _ := reader.ReadString('\n')
	return strings.TrimSpace(line)
}

func writeEnvFile(email, password, secret, anthropicKey, envPath string) error {
	if secret == "" {
		secret = os.Getenv("CW_SESSION_SECRET")
	}
	if secret == "" {
		b := make([]byte, 32)
		if _, err := rand.Read(b); err != nil {
			return fmt.Errorf("generate session secret: %w", err)
		}
		secret = hex.EncodeToString(b)
	}

	existing := make(map[string]string)
	if data, err := os.ReadFile(envPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			if k, v, ok := strings.Cut(line, "="); ok {
				existing[k] = v
			}
		}
	}

	existing["CW_ADMIN_EMAIL"] = email
	existing["CW_ADMIN_PASSWORD"] = password
	existing["CW_SESSION_SECRET"] = secret
	if anthropicKey != "" {
		existing["ANTHROPIC_API_KEY"] = anthropicKey
	}
	if _, ok := existing["POSTGRES_PASSWORD"]; !ok {
		b := make([]byte, 16)
		rand.Read(b)
		existing["POSTGRES_PASSWORD"] = hex.EncodeToString(b)
	}

	var out strings.Builder
	out.WriteString("# ChainWarden environment — generated by cwctl setup\n")
	out.WriteString("# Never commit this file.\n\n")

	out.WriteString("# Dashboard authentication\n")
	out.WriteString(fmt.Sprintf("CW_ADMIN_EMAIL=%s\n", existing["CW_ADMIN_EMAIL"]))
	out.WriteString(fmt.Sprintf("CW_ADMIN_PASSWORD=%s\n", existing["CW_ADMIN_PASSWORD"]))
	out.WriteString(fmt.Sprintf("CW_SESSION_SECRET=%s\n", existing["CW_SESSION_SECRET"]))
	out.WriteString("\n")

	if v, ok := existing["ANTHROPIC_API_KEY"]; ok && v != "" {
		out.WriteString("# AI features (advisory, patch, triage)\n")
		out.WriteString(fmt.Sprintf("ANTHROPIC_API_KEY=%s\n", v))
		out.WriteString("\n")
	}

	out.WriteString("# Docker-compose defaults\n")
	out.WriteString(fmt.Sprintf("POSTGRES_PASSWORD=%s\n", existing["POSTGRES_PASSWORD"]))

	for k, v := range existing {
		switch k {
		case "CW_ADMIN_EMAIL", "CW_ADMIN_PASSWORD", "CW_SESSION_SECRET",
			"ANTHROPIC_API_KEY", "POSTGRES_PASSWORD":
			continue
		}
		out.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}

	absPath, _ := filepath.Abs(envPath)
	if err := os.WriteFile(envPath, []byte(out.String()), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", envPath, err)
	}

	fmt.Println()
	fmt.Printf("  ✓  Configuration saved to %s\n", absPath)
	fmt.Println()
	fmt.Println("  Next steps:")
	fmt.Println("    cwctl serve                   # start API + dashboard")
	fmt.Println("    open http://localhost:8080     # open dashboard")
	fmt.Println()
	fmt.Println("  Or use Docker:")
	fmt.Println("    docker compose up -d           # start full stack")
	fmt.Println()

	return nil
}

func setupPrompt(reader *bufio.Reader, label, defaultVal string) string {
	if defaultVal != "" {
		masked := defaultVal
		if len(masked) > 6 {
			masked = masked[:3] + "***" + masked[len(masked)-3:]
		}
		fmt.Printf("  %s [%s]: ", label, masked)
	} else {
		fmt.Printf("  %s: ", label)
	}
	answer, _ := reader.ReadString('\n')
	answer = strings.TrimSpace(answer)
	if answer == "" {
		return defaultVal
	}
	return answer
}
