// Package intelligence provides real-time threat feed polling and AI-driven
// detection signature generation for ChainWarden scanners.
package intelligence

import "time"

// SignatureType identifies the kind of detection a signature performs.
type SignatureType string

const (
	SigTypoTarget     SignatureType = "typosquatting_target"
	SigMalwarePattern SignatureType = "malware_pattern"
	SigBlocklisted    SignatureType = "blocklisted_package"
	SigBehavioral     SignatureType = "behavioral_rule"
	SigMCPInjection   SignatureType = "mcp_injection_pattern"
	SigPickleRule     SignatureType = "pickle_rule"
)

// DetectionSignature is a single, typed detection rule generated by the
// intelligence agent or populated directly from threat feeds.
type DetectionSignature struct {
	// ID is auto-assigned: "CW-SIG-{unix_nano}"
	ID   string        `json:"id"`
	Type SignatureType `json:"type"`
	// Ecosystem is the package ecosystem this applies to, or "*" for all.
	Ecosystem string `json:"ecosystem"`
	// Target is the canonical package name for typosquat targets.
	Target string `json:"target,omitempty"`
	// Pattern is a hex-encoded byte sequence for malware_pattern entries.
	Pattern string `json:"pattern,omitempty"`
	// Package is the exact package name for blocklisted_package entries.
	Package string `json:"package,omitempty"`
	// Rule is a regex pattern string for behavioral_rule, mcp_injection_pattern, and pickle_rule entries.
	Rule        string `json:"rule,omitempty"`
	Severity    string `json:"severity"`
	Title       string `json:"title"`
	Description string `json:"description"`
	// Source indicates origin: osv | ossf | ai-generated | manual
	Source    string    `json:"source"`
	CVE       string    `json:"cve,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// SignatureStore is the on-disk JSON structure holding all detection signatures.
type SignatureStore struct {
	Version    int                  `json:"version"`
	UpdatedAt  time.Time            `json:"updated_at"`
	Signatures []DetectionSignature `json:"signatures"`
}
