import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { listSignatures, refreshIntelligence } from '../lib/api';
import { SeverityBadge } from '../components/SeverityBadge';
import { Database, RefreshCw, AlertCircle, Plus } from 'lucide-react';
import { useUIStore } from '../store/ui';
import type { DetectionSignature } from '../types/api';

const SIG_TYPES = ['', 'typosquat_target', 'malware_pattern', 'blocklisted_package', 'behavioral_rule', 'mcp_injection_pattern', 'pickle_rule'];
const ECOSYSTEMS = ['', 'npm', 'pypi', 'go', 'rubygems', 'crates', 'maven', 'huggingface', 'mcp'];

function sigTypeColor(t: string) {
  switch (t) {
    case 'blocklisted_package': return 'var(--color-critical)';
    case 'malware_pattern': return 'var(--color-critical)';
    case 'typosquat_target': return 'var(--color-warning)';
    case 'behavioral_rule': return '#60A5FA';
    default: return 'var(--color-muted)';
  }
}

export function IntelligencePage() {
  const [sigType, setSigType] = useState('');
  const [eco, setEco] = useState('');
  const qc = useQueryClient();
  const navigate = useUIStore(s => s.navigate);

  const sigs = useQuery({
    queryKey: ['signatures', sigType, eco],
    queryFn: () => listSignatures({ type: sigType || undefined, ecosystem: eco || undefined }),
  });

  const refresh = useMutation({
    mutationFn: refreshIntelligence,
    onSuccess: () => qc.invalidateQueries({ queryKey: ['signatures'] }),
  });

  const refreshStatusText = refresh.isSuccess
    ? (refresh.data.added > 0
        ? `+${refresh.data.added} new (${refresh.data.total} total)`
        : `Already up to date (${refresh.data.total} total)`)
    : refresh.isError
      ? (refresh.error as Error).message
      : null;

  const renderValue = (s: DetectionSignature) =>
    s.package ?? s.target ?? (s.rule ? s.rule.slice(0, 40) + '…' : s.pattern ?? '—');

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold font-mono" style={{ color: 'var(--fg)' }}>Intelligence Signatures</h1>
          <p className="text-sm mt-1" style={{ color: 'var(--color-muted)' }}>
            Real-time detection signatures generated by the AI agent from OSV, OpenSSF, and popularity feeds.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => navigate('/intel/new')}
            className="flex items-center gap-2 px-3 py-2 rounded text-sm font-mono"
            style={{ background: 'rgba(255,255,255,0.06)', color: 'var(--fg)', border: '1px solid rgba(255,255,255,0.12)' }}
          >
            <Plus size={13} />
            Create Signature
          </button>
          <button
            onClick={() => refresh.mutate()}
            disabled={refresh.isPending}
            className="flex items-center gap-2 px-3 py-2 rounded text-sm font-mono"
            style={{ background: 'rgba(0,255,135,0.1)', color: 'var(--color-safe)', border: '1px solid rgba(0,255,135,0.2)' }}
          >
            <RefreshCw size={13} className={refresh.isPending ? 'animate-spin' : ''} />
            {refresh.isPending ? 'Fetching…' : 'Refresh Feeds'}
          </button>
        </div>
      </div>

      {refreshStatusText && (
        <p
          className="text-xs font-mono"
          style={{ color: refresh.isError ? 'var(--color-critical)' : 'var(--color-safe)' }}
        >
          {refreshStatusText}
        </p>
      )}

      {/* Filters */}
      <div className="flex gap-3 flex-wrap">
        <select value={sigType} onChange={e => setSigType(e.target.value)}
          className="rounded px-3 py-2 text-sm font-mono"
          style={{ background: 'var(--surface)', color: 'var(--fg)', border: '1px solid rgba(255,255,255,0.12)' }}>
          {SIG_TYPES.map(t => <option key={t} value={t}>{t || 'All types'}</option>)}
        </select>
        <select value={eco} onChange={e => setEco(e.target.value)}
          className="rounded px-3 py-2 text-sm font-mono"
          style={{ background: 'var(--surface)', color: 'var(--fg)', border: '1px solid rgba(255,255,255,0.12)' }}>
          {ECOSYSTEMS.map(e => <option key={e} value={e}>{e || 'All ecosystems'}</option>)}
        </select>
        {sigs.data && (
          <span className="flex items-center text-sm" style={{ color: 'var(--color-muted)' }}>
            <Database size={13} className="mr-1" /> {sigs.data.total} signatures
          </span>
        )}
      </div>

      {/* Table */}
      <div className="rounded-lg" style={{ background: 'var(--surface)', border: '1px solid rgba(255,255,255,0.06)' }}>
        {sigs.isLoading && <div className="p-8 text-center text-sm" style={{ color: 'var(--color-muted)' }}>Loading…</div>}
        {sigs.isError && (
          <div className="flex items-center gap-2 p-4 text-sm" style={{ color: 'var(--color-critical)' }}>
            <AlertCircle size={14} />{(sigs.error as Error).message}
          </div>
        )}
        {sigs.data && (
          <>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
                    {['Type', 'Ecosystem', 'Value', 'Severity', 'Source', 'CVE'].map(h => (
                      <th key={h} className="text-left py-3 px-4 text-xs font-mono uppercase"
                        style={{ color: 'var(--color-muted)' }}>{h}</th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {sigs.data.signatures.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="py-14 text-center">
                        <div className="flex flex-col items-center gap-3">
                          <p className="text-sm" style={{ color: 'var(--fg)' }}>No signatures loaded</p>
                          <p className="text-xs" style={{ color: 'var(--color-muted)' }}>
                            Fetch community signatures from OSV, OpenSSF, and popularity feeds:
                          </p>
                          <code className="text-xs px-3 py-1.5 rounded font-mono"
                            style={{ background: 'rgba(255,255,255,0.06)', color: 'var(--color-safe)' }}>
                            cwctl update
                          </code>
                        </div>
                      </td>
                    </tr>
                  ) : sigs.data.signatures.map((s) => (
                    <tr key={s.id} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}
                      className="hover:bg-white/[0.02]">
                      <td className="py-2.5 px-4">
                        <span className="text-xs font-mono px-2 py-0.5 rounded"
                          style={{ color: sigTypeColor(s.type), background: 'rgba(255,255,255,0.05)' }}>
                          {s.type}
                        </span>
                      </td>
                      <td className="py-2.5 px-4 font-mono text-xs" style={{ color: 'var(--color-muted)' }}>{s.ecosystem}</td>
                      <td className="py-2.5 px-4 font-mono text-xs max-w-xs truncate" style={{ color: 'var(--fg)' }}
                        title={s.package ?? s.target ?? s.rule ?? s.pattern}>{renderValue(s)}</td>
                      <td className="py-2.5 px-4"><SeverityBadge severity={s.severity.toUpperCase() as never} /></td>
                      <td className="py-2.5 px-4 text-xs" style={{ color: 'var(--color-muted)' }}>{s.source}</td>
                      <td className="py-2.5 px-4 font-mono text-xs" style={{ color: 'var(--color-muted)' }}>{s.cve ?? '—'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {sigs.data.updated_at && (
              <div className="px-4 py-2 text-xs" style={{ color: 'var(--color-muted)', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                Last updated: {new Date(sigs.data.updated_at).toLocaleString()}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
