// Package spdx generates SPDX 2.3 SBOMs from ChainWarden build artifacts.
// AI model and MCP server packages use SPDX annotations to carry
// ChainWarden-specific security signals.
package spdx

import (
	"fmt"
	"io"
	"strings"
	"time"

	spdxjson "github.com/spdx/tools-golang/json"
	spdxcommon "github.com/spdx/tools-golang/spdx/v2/common"
	spdx23 "github.com/spdx/tools-golang/spdx/v2/v2_3"
	spdxtv "github.com/spdx/tools-golang/tagvalue"

	"github.com/deepak-ff/supply_chain/internal/core"
)

const (
	toolName    = "chainwarden-sbom"
	toolVersion = "0.1.0"
	nsBase      = "https://chainwarden.io/sbom"
)

// Generator produces SPDX 2.3 SBOMs.
type Generator struct{}

// New returns a new SPDX Generator.
func New() *Generator { return &Generator{} }

// GenerateJSON writes a SPDX 2.3 JSON SBOM for the artifact to w.
func (g *Generator) GenerateJSON(artifact core.BuiltArtifact, w io.Writer) error {
	doc := g.buildDocument(artifact)
	return spdxjson.Write(doc, w, spdxjson.Indent("  "))
}

// GenerateTV writes a SPDX 2.3 tag-value SBOM for the artifact to w.
func (g *Generator) GenerateTV(artifact core.BuiltArtifact, w io.Writer) error {
	doc := g.buildDocument(artifact)
	return spdxtv.Write(doc, w)
}

// buildDocument constructs the full SPDX 2.3 document from a BuiltArtifact.
func (g *Generator) buildDocument(artifact core.BuiltArtifact) *spdx23.Document {
	pkg := artifact.Source.Package
	now := time.Now().UTC()
	pkgID := sanitizeID(fmt.Sprintf("%s-%s-%s", pkg.Ecosystem, pkg.Name, pkg.Version))

	doc := &spdx23.Document{
		SPDXVersion:    spdx23.Version,
		DataLicense:    spdx23.DataLicense,
		SPDXIdentifier: "DOCUMENT",
		DocumentName:   fmt.Sprintf("%s-%s", pkg.Name, pkg.Version),
		DocumentNamespace: fmt.Sprintf("%s/%s/%s/%s-%s",
			nsBase, pkg.Ecosystem, pkg.Name, pkg.Version, now.Format("20060102T150405Z")),
		CreationInfo: &spdx23.CreationInfo{
			Created: now.Format(time.RFC3339),
			Creators: []spdxcommon.Creator{
				{CreatorType: "Tool", Creator: toolName + "-" + toolVersion},
			},
			CreatorComment: "Generated by ChainWarden hermetic build engine",
		},
		Packages: []*spdx23.Package{
			buildPackage(artifact, pkgID),
		},
		Relationships: []*spdx23.Relationship{
			{
				RefA:         spdxcommon.DocElementID{ElementRefID: "DOCUMENT"},
				RefB:         spdxcommon.DocElementID{ElementRefID: spdxcommon.ElementID(pkgID)},
				Relationship: spdxcommon.TypeRelationshipDescribe,
			},
		},
	}

	// Append ecosystem-specific annotations
	annotations := buildAnnotations(artifact, pkgID)
	doc.Annotations = annotations

	return doc
}

// buildPackage constructs the SPDX Package element.
func buildPackage(artifact core.BuiltArtifact, pkgID string) *spdx23.Package {
	pkg := artifact.Source.Package
	p := &spdx23.Package{
		PackageSPDXIdentifier:   spdxcommon.ElementID(pkgID),
		PackageName:             pkg.Name,
		PackageVersion:          pkg.Version,
		PackageDownloadLocation: downloadLocation(pkg),
		FilesAnalyzed:           false,
		PackageLicenseConcluded: "NOASSERTION",
		PackageLicenseDeclared:  "NOASSERTION",
		PackageCopyrightText:    "NOASSERTION",
		PackageChecksums: []spdxcommon.Checksum{
			{
				Algorithm: spdxcommon.SHA256,
				Value:     artifact.SHA256,
			},
		},
		PackageExternalReferences: buildExternalRefs(pkg),
	}

	if pkg.Checksum != "" {
		p.PackageSourceInfo = fmt.Sprintf("registry_sha256=%s", pkg.Checksum)
	}
	p.PackageSourceInfo += fmt.Sprintf(" built_at=%s hermetic=true network_connections=0",
		artifact.BuildTime.Format(time.RFC3339))

	return p
}

// buildAnnotations generates SPDX annotations for ChainWarden security signals.
// This is how we attach ecosystem-specific metadata without violating the SPDX spec.
func buildAnnotations(artifact core.BuiltArtifact, pkgID string) []*spdx23.Annotation {
	pkg := artifact.Source.Package
	var annotations []*spdx23.Annotation
	now := time.Now().UTC()

	addAnnotation := func(key, value string) {
		if value == "" {
			return
		}
		annotations = append(annotations, &spdx23.Annotation{
			AnnotationType: "REVIEW",
			AnnotationSPDXIdentifier: spdxcommon.DocElementID{
				ElementRefID: spdxcommon.ElementID(pkgID),
			},
			AnnotationDate: now.Format(time.RFC3339),
			Annotator: spdxcommon.Annotator{
				AnnotatorType: "Tool",
				Annotator:     toolName,
			},
			AnnotationComment: fmt.Sprintf("chainwarden:%s=%s", key, value),
		})
	}

	// Common annotations for all ecosystems
	addAnnotation("ecosystem", pkg.Ecosystem)
	addAnnotation("build_time", artifact.BuildTime.Format(time.RFC3339))
	addAnnotation("hermetic_build", "true")
	addAnnotation("network_connections", extractLogField(artifact.BuildLog, "network_connections"))

	switch pkg.Ecosystem {
	case "npm", "mcp":
		addAnnotation("install_scripts", extractLogField(artifact.BuildLog, "install_scripts"))
		addAnnotation("file_count", extractLogField(artifact.BuildLog, "file_count"))
		if pkg.Ecosystem == "mcp" {
			addAnnotation("mcp_tools_declared", extractLogField(artifact.BuildLog, "tools_declared"))
			addAnnotation("mcp_shadowed_tools", extractLogField(artifact.BuildLog, "shadowed_tools"))
			addAnnotation("mcp_injection_signals", extractLogField(artifact.BuildLog, "injection_signals"))
			addAnnotation("mcp_risk_score", extractLogField(artifact.BuildLog, "risk_score"))
		}
	case "pypi":
		addAnnotation("distribution_type", extractLogField(artifact.BuildLog, "distribution_type"))
		addAnnotation("has_setup_py", extractLogField(artifact.BuildLog, "has_setup_py"))
	case "maven":
		addAnnotation("jar_url", extractLogField(artifact.BuildLog, "jar_url"))
		addAnnotation("integrity_verified", extractLogField(artifact.BuildLog, "integrity_verified"))
	case "go":
		addAnnotation("sum_db_h1", extractLogField(artifact.BuildLog, "sum_db_h1"))
		addAnnotation("go_mod_declared", extractLogField(artifact.BuildLog, "go_mod_declared"))
	case "crates":
		addAnnotation("integrity_verified", extractLogField(artifact.BuildLog, "integrity_verified"))
	case "huggingface":
		addAnnotation("ai_safetensors_count", extractLogField(artifact.BuildLog, "safetensors_count"))
		addAnnotation("ai_pickle_count", extractLogField(artifact.BuildLog, "pickle_count"))
		addAnnotation("ai_onnx_count", extractLogField(artifact.BuildLog, "onnx_count"))
		addAnnotation("ai_suspicious_count", extractLogField(artifact.BuildLog, "suspicious_count"))
		addAnnotation("ai_pipeline_tag", extractLogField(artifact.BuildLog, "pipeline_tag"))
	}

	return annotations
}

// buildExternalRefs constructs SPDX external references (Package URLs, registries).
func buildExternalRefs(pkg core.PackageVersion) []*spdx23.PackageExternalReference {
	var refs []*spdx23.PackageExternalReference

	purl := buildPURL(pkg)
	if purl != "" {
		refs = append(refs, &spdx23.PackageExternalReference{
			Category: spdxcommon.CategoryPackageManager,
			RefType:  "purl",
			Locator:  purl,
		})
	}

	return refs
}

// downloadLocation returns the canonical download URL for SPDX PackageDownloadLocation.
func downloadLocation(pkg core.PackageVersion) string {
	if pkg.SourceURL != "" {
		return pkg.SourceURL
	}
	switch pkg.Ecosystem {
	case "npm", "mcp":
		return fmt.Sprintf("https://registry.npmjs.org/%s/-/%s-%s.tgz",
			pkg.Name, sanitizeName(pkg.Name), pkg.Version)
	case "pypi":
		return fmt.Sprintf("https://pypi.org/project/%s/%s/", pkg.Name, pkg.Version)
	case "maven":
		parts := strings.SplitN(pkg.Name, ":", 2)
		if len(parts) == 2 {
			groupPath := strings.ReplaceAll(parts[0], ".", "/")
			return fmt.Sprintf("https://repo1.maven.org/maven2/%s/%s/%s/%s-%s.jar",
				groupPath, parts[1], pkg.Version, parts[1], pkg.Version)
		}
	case "go":
		return fmt.Sprintf("https://proxy.golang.org/%s/@v/%s.zip", pkg.Name, pkg.Version)
	case "rubygems":
		return fmt.Sprintf("https://rubygems.org/gems/%s-%s.gem", pkg.Name, pkg.Version)
	case "crates":
		return fmt.Sprintf("https://static.crates.io/crates/%s/%s-%s.crate", pkg.Name, pkg.Name, pkg.Version)
	case "huggingface":
		return fmt.Sprintf("https://huggingface.co/%s", pkg.Name)
	}
	return "NOASSERTION"
}

// buildPURL returns a Package URL string for a given package.
func buildPURL(pkg core.PackageVersion) string {
	switch pkg.Ecosystem {
	case "npm", "mcp":
		return fmt.Sprintf("pkg:npm/%s@%s", pkg.Name, pkg.Version)
	case "pypi":
		return fmt.Sprintf("pkg:pypi/%s@%s", strings.ToLower(pkg.Name), pkg.Version)
	case "maven":
		parts := strings.SplitN(pkg.Name, ":", 2)
		if len(parts) == 2 {
			return fmt.Sprintf("pkg:maven/%s/%s@%s",
				strings.ReplaceAll(parts[0], ".", "/"), parts[1], pkg.Version)
		}
		return fmt.Sprintf("pkg:maven/%s@%s", pkg.Name, pkg.Version)
	case "go":
		return fmt.Sprintf("pkg:golang/%s@%s", pkg.Name, pkg.Version)
	case "rubygems":
		return fmt.Sprintf("pkg:gem/%s@%s", pkg.Name, pkg.Version)
	case "crates":
		return fmt.Sprintf("pkg:cargo/%s@%s", pkg.Name, pkg.Version)
	case "huggingface":
		return fmt.Sprintf("pkg:huggingface/%s@%s", pkg.Name, pkg.Version)
	}
	return ""
}

// sanitizeID replaces chars illegal in SPDX identifiers with dashes.
func sanitizeID(s string) string {
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '.' {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	return b.String()
}

// sanitizeName strips the npm scope prefix for URL construction.
func sanitizeName(name string) string {
	if idx := strings.LastIndex(name, "/"); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

// extractLogField retrieves the value of a "key: value" line from a build log.
func extractLogField(log, key string) string {
	prefix := key + ":"
	for _, line := range strings.Split(log, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(trimmed, prefix))
		}
	}
	return ""
}
