// Code generated by sqlc. DO NOT EDIT.
// source: schema.sql

package dbsqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Package struct {
	ID        int64              `db:"id"         json:"id"`
	Ecosystem string             `db:"ecosystem"  json:"ecosystem"`
	Name      string             `db:"name"       json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type PackageVersion struct {
	ID          int64              `db:"id"           json:"id"`
	PackageID   int64              `db:"package_id"   json:"package_id"`
	Version     string             `db:"version"      json:"version"`
	SourceURL   string             `db:"source_url"   json:"source_url"`
	Checksum    string             `db:"checksum"     json:"checksum"`
	PublishedAt pgtype.Timestamptz `db:"published_at" json:"published_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"   json:"created_at"`
}

type ScanResult struct {
	ID               BIGSERIAL          `db:"id"                  json:"id"`
	PackageVersionID int64              `db:"package_version_id"  json:"package_version_id"`
	Sha256           string             `db:"sha256"              json:"sha256"`
	Status           string             `db:"status"              json:"status"`
	TotalFindings    int32              `db:"total_findings"      json:"total_findings"`
	CriticalFindings int32              `db:"critical_findings"   json:"critical_findings"`
	HighFindings     int32              `db:"high_findings"       json:"high_findings"`
	MediumFindings   int32              `db:"medium_findings"     json:"medium_findings"`
	LowFindings      int32              `db:"low_findings"        json:"low_findings"`
	HighestSeverity  string             `db:"highest_severity"    json:"highest_severity"`
	FindingsJson     []byte             `db:"findings_json"       json:"findings_json"`
	ErrorMessage     string             `db:"error_message"       json:"error_message"`
	ScannedAt        pgtype.Timestamptz `db:"scanned_at"          json:"scanned_at"`
}

type Advisory struct {
	ID                      int64              `db:"id"                       json:"id"`
	PackageVersionID        int64              `db:"package_version_id"       json:"package_version_id"`
	Severity                string             `db:"severity"                 json:"severity"`
	Confidence              float64            `db:"confidence"               json:"confidence"`
	AdvisoryText            string             `db:"advisory_text"            json:"advisory_text"`
	ExploitabilityRationale string             `db:"exploitability_rationale" json:"exploitability_rationale"`
	AgenticRisk             *string            `db:"agentic_risk"             json:"agentic_risk"`
	RecommendedAction       string             `db:"recommended_action"       json:"recommended_action"`
	PatchSuggestion         *string            `db:"patch_suggestion"         json:"patch_suggestion"`
	GeneratedAt             pgtype.Timestamptz `db:"generated_at"             json:"generated_at"`
}

type Attestation struct {
	ID               int64              `db:"id"                  json:"id"`
	PackageVersionID int64              `db:"package_version_id"  json:"package_version_id"`
	Sha256           string             `db:"sha256"              json:"sha256"`
	Signature        string             `db:"signature"           json:"signature"`
	PublicKey        string             `db:"public_key"          json:"public_key"`
	RekorLogID       string             `db:"rekor_log_id"        json:"rekor_log_id"`
	RekorIndex       int64              `db:"rekor_index"         json:"rekor_index"`
	RekorURL         string             `db:"rekor_url"           json:"rekor_url"`
	AttestationJson  []byte             `db:"attestation_json"    json:"attestation_json"`
	SignedAt         pgtype.Timestamptz `db:"signed_at"           json:"signed_at"`
}

// BIGSERIAL is an alias kept for clarity; maps to int64 at the Go level.
type BIGSERIAL = int64

// DashboardStatsRow is the result of the DashboardStats aggregate query.
type DashboardStatsRow struct {
	TotalPackages    int64 `db:"total_packages"    json:"total_packages"`
	TotalVersions    int64 `db:"total_versions"    json:"total_versions"`
	TotalFindings    int64 `db:"total_findings"    json:"total_findings"`
	CriticalFindings int64 `db:"critical_findings" json:"critical_findings"`
	HighFindings     int64 `db:"high_findings"     json:"high_findings"`
	MediumFindings   int64 `db:"medium_findings"   json:"medium_findings"`
	LowFindings      int64 `db:"low_findings"      json:"low_findings"`
	ScannedToday     int64 `db:"scanned_today"     json:"scanned_today"`
}

// DashboardTimelineRow is one day of aggregate finding counts.
type DashboardTimelineRow struct {
	Day      pgtype.Timestamptz `db:"day"      json:"day"`
	Critical int64              `db:"critical" json:"critical"`
	High     int64              `db:"high"     json:"high"`
	Medium   int64              `db:"medium"   json:"medium"`
	Low      int64              `db:"low"      json:"low"`
}

// RecentScanRow is the result of the ListRecentScans query.
type RecentScanRow struct {
	Ecosystem        string             `db:"ecosystem"         json:"ecosystem"`
	Name             string             `db:"name"              json:"name"`
	Version          string             `db:"version"           json:"version"`
	HighestSeverity  string             `db:"highest_severity"  json:"highest_severity"`
	TotalFindings    int32              `db:"total_findings"    json:"total_findings"`
	CriticalFindings int32              `db:"critical_findings" json:"critical_findings"`
	HighFindings     int32              `db:"high_findings"     json:"high_findings"`
	MediumFindings   int32              `db:"medium_findings"   json:"medium_findings"`
	LowFindings      int32              `db:"low_findings"      json:"low_findings"`
	ScannedAt        pgtype.Timestamptz `db:"scanned_at"        json:"scanned_at"`
}

// PackageWithVersionCount is the result of ListPackages / GetPackage.
type PackageWithVersionCount struct {
	Package
	VersionCount int64 `db:"version_count" json:"version_count"`
}

// AttestationWithPackage joins attestation with package coordinates.
type AttestationWithPackage struct {
	Attestation
	Ecosystem string `db:"ecosystem" json:"ecosystem"`
	PkgName   string `db:"name"      json:"name"`
	Version   string `db:"version"   json:"version"`
}

// AllowlistEntry is a package explicitly trusted to bypass policy enforcement.
type AllowlistEntry struct {
	ID        int64              `db:"id"         json:"id"`
	Ecosystem string             `db:"ecosystem"  json:"ecosystem"`
	Package   string             `db:"package"    json:"package"`
	Reason    string             `db:"reason"     json:"reason"`
	AddedBy   string             `db:"added_by"   json:"added_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Alert is a persisted security event surfaced to operators.
type Alert struct {
	ID          int64              `db:"id"           json:"id"`
	Type        string             `db:"type"         json:"type"`
	Message     string             `db:"message"      json:"message"`
	Severity    string             `db:"severity"     json:"severity"`
	PackageName *string            `db:"package_name" json:"package_name,omitempty"`
	Ecosystem   *string            `db:"ecosystem"    json:"ecosystem,omitempty"`
	Version     *string            `db:"version"      json:"version,omitempty"`
	Metadata    []byte             `db:"metadata"     json:"metadata,omitempty"`
	Dismissed   bool               `db:"dismissed"    json:"dismissed"`
	OccurredAt  pgtype.Timestamptz `db:"occurred_at"  json:"occurred_at"`
}

// NullTime is a helper for optional timestamps.
type NullTime struct {
	Time  time.Time
	Valid bool
}
