// Code generated by sqlc. DO NOT EDIT.

package dbsqlc

import "github.com/jackc/pgx/v5/pgtype"

// UpsertPackageVersionParams are the inputs for UpsertPackageVersion.
type UpsertPackageVersionParams struct {
	PackageID   int64              `db:"package_id"`
	Version     string             `db:"version"`
	SourceURL   string             `db:"source_url"`
	Checksum    string             `db:"checksum"`
	PublishedAt pgtype.Timestamptz `db:"published_at"`
}

// UpsertScanResultParams are the inputs for UpsertScanResult.
type UpsertScanResultParams struct {
	PackageVersionID int64  `db:"package_version_id"`
	Sha256           string `db:"sha256"`
	Status           string `db:"status"`
	TotalFindings    int32  `db:"total_findings"`
	CriticalFindings int32  `db:"critical_findings"`
	HighFindings     int32  `db:"high_findings"`
	MediumFindings   int32  `db:"medium_findings"`
	LowFindings      int32  `db:"low_findings"`
	HighestSeverity  string `db:"highest_severity"`
	FindingsJson     []byte `db:"findings_json"`
	ErrorMessage     string `db:"error_message"`
}

// InsertAttestationParams are the inputs for InsertAttestation.
type InsertAttestationParams struct {
	PackageVersionID int64  `db:"package_version_id"`
	Sha256           string `db:"sha256"`
	Signature        string `db:"signature"`
	PublicKey        string `db:"public_key"`
	RekorLogID       string `db:"rekor_log_id"`
	RekorIndex       int64  `db:"rekor_index"`
	RekorURL         string `db:"rekor_url"`
	AttestationJson  []byte `db:"attestation_json"`
}
