// Code generated by sqlc. DO NOT EDIT.

package dbsqlc

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

// DBTX is the interface satisfied by both *pgx.Conn and *pgxpool.Pool.
type DBTX interface {
	QueryRow(ctx context.Context, sql string, args ...any) pgx.Row
	Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error)
	Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)
}

// Queries implements Querier against a live database connection.
type Queries struct {
	db DBTX
}

// New returns a Queries bound to db.
func New(db DBTX) *Queries { return &Queries{db: db} }

var _ Querier = (*Queries)(nil)

// ─── packages ─────────────────────────────────────────────────────────────────

const upsertPackageSQL = `
INSERT INTO packages (ecosystem, name, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (ecosystem, name) DO UPDATE SET updated_at = now()
RETURNING id, ecosystem, name, created_at, updated_at`

func (q *Queries) UpsertPackage(ctx context.Context, ecosystem, name string) (Package, error) {
	var p Package
	row := q.db.QueryRow(ctx, upsertPackageSQL, ecosystem, name)
	err := row.Scan(&p.ID, &p.Ecosystem, &p.Name, &p.CreatedAt, &p.UpdatedAt)
	return p, err
}

const getPackageSQL = `
SELECT p.id, p.ecosystem, p.name, p.created_at, p.updated_at, COUNT(pv.id) AS version_count
FROM packages p
LEFT JOIN package_versions pv ON pv.package_id = p.id
WHERE p.ecosystem = $1 AND p.name = $2
GROUP BY p.id`

func (q *Queries) GetPackage(ctx context.Context, ecosystem, name string) (PackageWithVersionCount, error) {
	var r PackageWithVersionCount
	row := q.db.QueryRow(ctx, getPackageSQL, ecosystem, name)
	err := row.Scan(&r.ID, &r.Ecosystem, &r.Name, &r.CreatedAt, &r.UpdatedAt, &r.VersionCount)
	return r, err
}

const listPackagesSQL = `
SELECT p.id, p.ecosystem, p.name, p.created_at, p.updated_at, COUNT(pv.id) AS version_count
FROM packages p
LEFT JOIN package_versions pv ON pv.package_id = p.id
WHERE ($1::text = '' OR p.ecosystem = $1)
GROUP BY p.id
ORDER BY p.updated_at DESC
LIMIT $2 OFFSET $3`

func (q *Queries) ListPackages(ctx context.Context, ecosystem string, limit, offset int32) ([]PackageWithVersionCount, error) {
	rows, err := q.db.Query(ctx, listPackagesSQL, ecosystem, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []PackageWithVersionCount
	for rows.Next() {
		var r PackageWithVersionCount
		if err := rows.Scan(&r.ID, &r.Ecosystem, &r.Name, &r.CreatedAt, &r.UpdatedAt, &r.VersionCount); err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

const countPackagesSQL = `SELECT COUNT(*) FROM packages WHERE ($1::text = '' OR ecosystem = $1)`

func (q *Queries) CountPackages(ctx context.Context, ecosystem string) (int64, error) {
	var n int64
	return n, q.db.QueryRow(ctx, countPackagesSQL, ecosystem).Scan(&n)
}

// ─── package versions ─────────────────────────────────────────────────────────

const upsertPackageVersionSQL = `
INSERT INTO package_versions (package_id, version, source_url, checksum, published_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (package_id, version) DO UPDATE
    SET source_url = EXCLUDED.source_url,
        checksum   = EXCLUDED.checksum
RETURNING id, package_id, version, source_url, checksum, published_at, created_at`

func (q *Queries) UpsertPackageVersion(ctx context.Context, arg UpsertPackageVersionParams) (PackageVersion, error) {
	var pv PackageVersion
	row := q.db.QueryRow(ctx, upsertPackageVersionSQL,
		arg.PackageID, arg.Version, arg.SourceURL, arg.Checksum, arg.PublishedAt,
	)
	err := row.Scan(&pv.ID, &pv.PackageID, &pv.Version, &pv.SourceURL, &pv.Checksum, &pv.PublishedAt, &pv.CreatedAt)
	return pv, err
}

const listVersionsSQL = `
SELECT pv.id, pv.package_id, pv.version, pv.source_url, pv.checksum, pv.published_at, pv.created_at
FROM package_versions pv
JOIN packages p ON p.id = pv.package_id
WHERE p.ecosystem = $1 AND p.name = $2
ORDER BY pv.created_at DESC`

func (q *Queries) ListVersions(ctx context.Context, ecosystem, name string) ([]PackageVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsSQL, ecosystem, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []PackageVersion
	for rows.Next() {
		var pv PackageVersion
		if err := rows.Scan(&pv.ID, &pv.PackageID, &pv.Version, &pv.SourceURL, &pv.Checksum, &pv.PublishedAt, &pv.CreatedAt); err != nil {
			return nil, err
		}
		result = append(result, pv)
	}
	return result, rows.Err()
}

const getPackageVersionSQL = `
SELECT pv.id, pv.package_id, pv.version, pv.source_url, pv.checksum, pv.published_at, pv.created_at
FROM package_versions pv
JOIN packages p ON p.id = pv.package_id
WHERE p.ecosystem = $1 AND p.name = $2 AND pv.version = $3`

func (q *Queries) GetPackageVersion(ctx context.Context, ecosystem, name, version string) (PackageVersion, error) {
	var pv PackageVersion
	row := q.db.QueryRow(ctx, getPackageVersionSQL, ecosystem, name, version)
	err := row.Scan(&pv.ID, &pv.PackageID, &pv.Version, &pv.SourceURL, &pv.Checksum, &pv.PublishedAt, &pv.CreatedAt)
	return pv, err
}

// ─── scan results ─────────────────────────────────────────────────────────────

const upsertScanResultSQL = `
INSERT INTO scan_results (
    package_version_id, sha256, status,
    total_findings, critical_findings, high_findings, medium_findings, low_findings,
    highest_severity, findings_json, error_message, scanned_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,now())
ON CONFLICT (package_version_id) DO UPDATE
    SET sha256            = EXCLUDED.sha256,
        status            = EXCLUDED.status,
        total_findings    = EXCLUDED.total_findings,
        critical_findings = EXCLUDED.critical_findings,
        high_findings     = EXCLUDED.high_findings,
        medium_findings   = EXCLUDED.medium_findings,
        low_findings      = EXCLUDED.low_findings,
        highest_severity  = EXCLUDED.highest_severity,
        findings_json     = EXCLUDED.findings_json,
        error_message     = EXCLUDED.error_message,
        scanned_at        = now()
RETURNING id, package_version_id, sha256, status,
          total_findings, critical_findings, high_findings, medium_findings, low_findings,
          highest_severity, findings_json, error_message, scanned_at`

func (q *Queries) UpsertScanResult(ctx context.Context, arg UpsertScanResultParams) (ScanResult, error) {
	var sr ScanResult
	row := q.db.QueryRow(ctx, upsertScanResultSQL,
		arg.PackageVersionID, arg.Sha256, arg.Status,
		arg.TotalFindings, arg.CriticalFindings, arg.HighFindings, arg.MediumFindings, arg.LowFindings,
		arg.HighestSeverity, arg.FindingsJson, arg.ErrorMessage,
	)
	err := row.Scan(
		&sr.ID, &sr.PackageVersionID, &sr.Sha256, &sr.Status,
		&sr.TotalFindings, &sr.CriticalFindings, &sr.HighFindings, &sr.MediumFindings, &sr.LowFindings,
		&sr.HighestSeverity, &sr.FindingsJson, &sr.ErrorMessage, &sr.ScannedAt,
	)
	return sr, err
}

const getScanResultSQL = `
SELECT sr.id, sr.package_version_id, sr.sha256, sr.status,
       sr.total_findings, sr.critical_findings, sr.high_findings, sr.medium_findings, sr.low_findings,
       sr.highest_severity, sr.findings_json, sr.error_message, sr.scanned_at
FROM scan_results sr
JOIN package_versions pv ON pv.id = sr.package_version_id
JOIN packages p ON p.id = pv.package_id
WHERE p.ecosystem = $1 AND p.name = $2 AND pv.version = $3`

func (q *Queries) GetScanResult(ctx context.Context, ecosystem, name, version string) (ScanResult, error) {
	var sr ScanResult
	row := q.db.QueryRow(ctx, getScanResultSQL, ecosystem, name, version)
	err := row.Scan(
		&sr.ID, &sr.PackageVersionID, &sr.Sha256, &sr.Status,
		&sr.TotalFindings, &sr.CriticalFindings, &sr.HighFindings, &sr.MediumFindings, &sr.LowFindings,
		&sr.HighestSeverity, &sr.FindingsJson, &sr.ErrorMessage, &sr.ScannedAt,
	)
	return sr, err
}

const listRecentScansSQL = `
SELECT p.ecosystem, p.name, pv.version,
       sr.highest_severity, sr.total_findings,
       sr.critical_findings, sr.high_findings, sr.medium_findings, sr.low_findings,
       sr.scanned_at
FROM scan_results sr
JOIN package_versions pv ON pv.id = sr.package_version_id
JOIN packages p ON p.id = pv.package_id
WHERE sr.status = 'complete'
ORDER BY sr.scanned_at DESC
LIMIT $1`

func (q *Queries) ListRecentScans(ctx context.Context, limit int32) ([]RecentScanRow, error) {
	rows, err := q.db.Query(ctx, listRecentScansSQL, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []RecentScanRow
	for rows.Next() {
		var r RecentScanRow
		if err := rows.Scan(
			&r.Ecosystem, &r.Name, &r.Version,
			&r.HighestSeverity, &r.TotalFindings,
			&r.CriticalFindings, &r.HighFindings, &r.MediumFindings, &r.LowFindings,
			&r.ScannedAt,
		); err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

const dashboardStatsSQL = `
SELECT
    (SELECT COUNT(*)  FROM packages)                                                    AS total_packages,
    (SELECT COUNT(*)  FROM package_versions)                                            AS total_versions,
    (SELECT COALESCE(SUM(total_findings),   0) FROM scan_results)                       AS total_findings,
    (SELECT COALESCE(SUM(critical_findings),0) FROM scan_results)                       AS critical_findings,
    (SELECT COALESCE(SUM(high_findings),    0) FROM scan_results)                       AS high_findings,
    (SELECT COALESCE(SUM(medium_findings),  0) FROM scan_results)                       AS medium_findings,
    (SELECT COALESCE(SUM(low_findings),     0) FROM scan_results)                       AS low_findings,
    (SELECT COUNT(*) FROM scan_results WHERE scanned_at >= now() - interval '24 hours') AS scanned_today`

func (q *Queries) DashboardStats(ctx context.Context) (DashboardStatsRow, error) {
	var r DashboardStatsRow
	row := q.db.QueryRow(ctx, dashboardStatsSQL)
	err := row.Scan(
		&r.TotalPackages, &r.TotalVersions,
		&r.TotalFindings, &r.CriticalFindings, &r.HighFindings,
		&r.MediumFindings, &r.LowFindings,
		&r.ScannedToday,
	)
	return r, err
}

const dashboardTimelineSQL = `
SELECT
    date_trunc('day', scanned_at)                     AS day,
    COALESCE(SUM(critical_findings), 0)               AS critical,
    COALESCE(SUM(high_findings), 0)                   AS high,
    COALESCE(SUM(medium_findings), 0)                 AS medium,
    COALESCE(SUM(low_findings), 0)                    AS low
FROM scan_results
WHERE scanned_at >= now() - ($1::int * interval '1 day')
GROUP BY 1
ORDER BY 1`

func (q *Queries) DashboardTimeline(ctx context.Context, days int32) ([]DashboardTimelineRow, error) {
	rows, err := q.db.Query(ctx, dashboardTimelineSQL, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []DashboardTimelineRow
	for rows.Next() {
		var r DashboardTimelineRow
		if err := rows.Scan(&r.Day, &r.Critical, &r.High, &r.Medium, &r.Low); err != nil {
			return nil, err
		}
		result = append(result, r)
	}
	return result, rows.Err()
}

// ─── attestations ─────────────────────────────────────────────────────────────

const insertAttestationSQL = `
INSERT INTO attestations (
    package_version_id, sha256, signature, public_key,
    rekor_log_id, rekor_index, rekor_url, attestation_json, signed_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,now())
RETURNING id, package_version_id, sha256, signature, public_key,
          rekor_log_id, rekor_index, rekor_url, attestation_json, signed_at`

func (q *Queries) InsertAttestation(ctx context.Context, arg InsertAttestationParams) (Attestation, error) {
	var a Attestation
	row := q.db.QueryRow(ctx, insertAttestationSQL,
		arg.PackageVersionID, arg.Sha256, arg.Signature, arg.PublicKey,
		arg.RekorLogID, arg.RekorIndex, arg.RekorURL, arg.AttestationJson,
	)
	err := row.Scan(
		&a.ID, &a.PackageVersionID, &a.Sha256, &a.Signature, &a.PublicKey,
		&a.RekorLogID, &a.RekorIndex, &a.RekorURL, &a.AttestationJson, &a.SignedAt,
	)
	return a, err
}

const getAttestationBySHA256SQL = `
SELECT att.id, att.package_version_id, att.sha256, att.signature, att.public_key,
       att.rekor_log_id, att.rekor_index, att.rekor_url, att.attestation_json, att.signed_at,
       p.ecosystem, p.name, pv.version
FROM attestations att
JOIN package_versions pv ON pv.id = att.package_version_id
JOIN packages p ON p.id = pv.package_id
WHERE att.sha256 = $1
ORDER BY att.signed_at DESC
LIMIT 1`

func (q *Queries) GetAttestationBySHA256(ctx context.Context, sha256 string) (AttestationWithPackage, error) {
	var a AttestationWithPackage
	row := q.db.QueryRow(ctx, getAttestationBySHA256SQL, sha256)
	err := row.Scan(
		&a.ID, &a.PackageVersionID, &a.Sha256, &a.Signature, &a.PublicKey,
		&a.RekorLogID, &a.RekorIndex, &a.RekorURL, &a.AttestationJson, &a.SignedAt,
		&a.Ecosystem, &a.PkgName, &a.Version,
	)
	return a, err
}

// ─── allowlist ────────────────────────────────────────────────────────────────

const listAllowlistSQL = `
SELECT id, ecosystem, package, reason, added_by, created_at
FROM allowlist
ORDER BY created_at DESC`

func (q *Queries) ListAllowlist(ctx context.Context) ([]AllowlistEntry, error) {
	rows, err := q.db.Query(ctx, listAllowlistSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []AllowlistEntry
	for rows.Next() {
		var e AllowlistEntry
		if err := rows.Scan(&e.ID, &e.Ecosystem, &e.Package, &e.Reason, &e.AddedBy, &e.CreatedAt); err != nil {
			return nil, err
		}
		result = append(result, e)
	}
	return result, rows.Err()
}

const upsertAllowlistSQL = `
INSERT INTO allowlist (ecosystem, package, reason, added_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ecosystem, package) DO UPDATE
    SET reason    = EXCLUDED.reason,
        added_by  = EXCLUDED.added_by
RETURNING id, ecosystem, package, reason, added_by, created_at`

func (q *Queries) UpsertAllowlist(ctx context.Context, ecosystem, pkg, reason, addedBy string) (AllowlistEntry, error) {
	var e AllowlistEntry
	row := q.db.QueryRow(ctx, upsertAllowlistSQL, ecosystem, pkg, reason, addedBy)
	err := row.Scan(&e.ID, &e.Ecosystem, &e.Package, &e.Reason, &e.AddedBy, &e.CreatedAt)
	return e, err
}

const deleteAllowlistSQL = `DELETE FROM allowlist WHERE id = $1`

func (q *Queries) DeleteAllowlist(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAllowlistSQL, id)
	return err
}

const isAllowlistedSQL = `
SELECT COUNT(*) FROM allowlist
WHERE package = $1 AND (ecosystem = '' OR ecosystem = $2)`

func (q *Queries) IsAllowlisted(ctx context.Context, pkg, ecosystem string) (bool, error) {
	var n int64
	err := q.db.QueryRow(ctx, isAllowlistedSQL, pkg, ecosystem).Scan(&n)
	return n > 0, err
}

// ─── alerts ───────────────────────────────────────────────────────────────────

const insertAlertSQL = `
INSERT INTO alerts (type, message, severity, package_name, ecosystem, version, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, message, severity, package_name, ecosystem, version, metadata, dismissed, occurred_at`

func (q *Queries) InsertAlert(ctx context.Context, typ, message, severity string, pkgName, eco, ver *string, meta []byte) (Alert, error) {
	var a Alert
	row := q.db.QueryRow(ctx, insertAlertSQL, typ, message, severity, pkgName, eco, ver, meta)
	err := row.Scan(&a.ID, &a.Type, &a.Message, &a.Severity, &a.PackageName, &a.Ecosystem, &a.Version, &a.Metadata, &a.Dismissed, &a.OccurredAt)
	return a, err
}

const listAlertsSQL = `
SELECT id, type, message, severity, package_name, ecosystem, version, metadata, dismissed, occurred_at
FROM alerts
WHERE ($1::boolean IS NULL OR dismissed = $1)
  AND ($2::text = '' OR severity = $2)
ORDER BY occurred_at DESC
LIMIT $3 OFFSET $4`

func (q *Queries) ListAlerts(ctx context.Context, dismissed *bool, severity string, limit, offset int32) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsSQL, dismissed, severity, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var result []Alert
	for rows.Next() {
		var a Alert
		if err := rows.Scan(&a.ID, &a.Type, &a.Message, &a.Severity, &a.PackageName, &a.Ecosystem, &a.Version, &a.Metadata, &a.Dismissed, &a.OccurredAt); err != nil {
			return nil, err
		}
		result = append(result, a)
	}
	return result, rows.Err()
}

const dismissAlertSQL = `UPDATE alerts SET dismissed = true WHERE id = $1`

func (q *Queries) DismissAlert(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, dismissAlertSQL, id)
	return err
}

const countAlertsSQL = `
SELECT COUNT(*) FROM alerts
WHERE ($1::boolean IS NULL OR dismissed = $1)
  AND ($2::text = '' OR severity = $2)`

func (q *Queries) CountAlerts(ctx context.Context, dismissed *bool, severity string) (int64, error) {
	var n int64
	return n, q.db.QueryRow(ctx, countAlertsSQL, dismissed, severity).Scan(&n)
}

// errNoRows checks if err is a pgx not-found error.
func errNoRows(err error) bool {
	return err != nil && err.Error() == "no rows in result set"
}

// suppress unused import lint
var _ = fmt.Sprintf
var _ pgtype.Timestamptz
