// Code generated by sqlc. DO NOT EDIT.

package dbsqlc

import "context"

// Querier is the interface implemented by *Queries and *SQLiteQueries.
type Querier interface {
	// packages
	UpsertPackage(ctx context.Context, ecosystem, name string) (Package, error)
	GetPackage(ctx context.Context, ecosystem, name string) (PackageWithVersionCount, error)
	ListPackages(ctx context.Context, ecosystem string, limit, offset int32) ([]PackageWithVersionCount, error)
	CountPackages(ctx context.Context, ecosystem string) (int64, error)

	// package versions
	UpsertPackageVersion(ctx context.Context, arg UpsertPackageVersionParams) (PackageVersion, error)
	ListVersions(ctx context.Context, ecosystem, name string) ([]PackageVersion, error)
	GetPackageVersion(ctx context.Context, ecosystem, name, version string) (PackageVersion, error)

	// scan results
	UpsertScanResult(ctx context.Context, arg UpsertScanResultParams) (ScanResult, error)
	GetScanResult(ctx context.Context, ecosystem, name, version string) (ScanResult, error)
	ListRecentScans(ctx context.Context, limit int32) ([]RecentScanRow, error)
	DashboardStats(ctx context.Context) (DashboardStatsRow, error)
	DashboardTimeline(ctx context.Context, days int32) ([]DashboardTimelineRow, error)

	// attestations
	InsertAttestation(ctx context.Context, arg InsertAttestationParams) (Attestation, error)
	GetAttestationBySHA256(ctx context.Context, sha256 string) (AttestationWithPackage, error)

	// allowlist
	ListAllowlist(ctx context.Context) ([]AllowlistEntry, error)
	UpsertAllowlist(ctx context.Context, ecosystem, pkg, reason, addedBy string) (AllowlistEntry, error)
	DeleteAllowlist(ctx context.Context, id int64) error
	IsAllowlisted(ctx context.Context, pkg, ecosystem string) (bool, error)

	// alerts
	InsertAlert(ctx context.Context, typ, message, severity string, pkgName, eco, ver *string, meta []byte) (Alert, error)
	ListAlerts(ctx context.Context, dismissed *bool, severity string, limit, offset int32) ([]Alert, error)
	DismissAlert(ctx context.Context, id int64) error
	CountAlerts(ctx context.Context, dismissed *bool, severity string) (int64, error)
}
